version: '3'

services:
  auth_db:
    image: scs_db:latest
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: admin
      DB_SCHEMA: auth_schema
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: test -f /tmp/db_ready
      retries: 100
  server_db:
    image: scs_db:latest
    container_name: server_db
    environment:
      POSTGRES_DB: server_db
      POSTGRES_USER: server_user
      POSTGRES_PASSWORD: admin
      DB_SCHEMA: server_schema
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: test -f /tmp/db_ready
      retries: 100
volumes:
  db:
    driver: local
